from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
import torch

from predict_weights import rebuild_model
from train import StockPanelDataset


def _safe_load_checkpoint(path: str, device: str) -> dict:
    """Load a torch checkpoint while staying compatible with older/newer PyTorch."""
    try:
        return torch.load(path, map_location=device, weights_only=False)
    except TypeError:
        return torch.load(path, map_location=device)


def _rank_valid_indices(scores: np.ndarray, valid: np.ndarray, descending: bool = True) -> list[int]:
    """Return stock indices ranked by score, filtering invalid / non-finite entries."""
    valid = valid.astype(bool) & np.isfinite(scores)
    if not valid.any():
        return []

    masked_scores = np.where(valid, scores, -np.inf if descending else np.inf)
    order = np.argsort(masked_scores)
    if descending:
        order = order[::-1]
    return [int(i) for i in order if valid[i]]


def _make_equal_weight_vector(num_stocks: int, holdings: list[int]) -> np.ndarray:
    w = np.zeros(num_stocks, dtype=np.float32)
    if holdings:
        w[np.array(holdings, dtype=int)] = 1.0 / len(holdings)
    return w


def _calc_max_drawdown(nav: pd.Series) -> float:
    if nav.empty:
        return float("nan")
    return float((nav / nav.cummax() - 1.0).min())


def _format_codes(indices: list[int], stocks: np.ndarray) -> str:
    return ";".join(stocks[indices].tolist()) if indices else ""


def _feature_values(x: torch.Tensor, feature_cols: list[str], names: list[str]) -> dict[str, np.ndarray]:
    last = x[:, -1, :].numpy().astype(np.float64)
    out: dict[str, np.ndarray] = {}
    for name in names:
        out[name] = last[:, feature_cols.index(name)] if name in feature_cols else np.zeros(last.shape[0], dtype=float)
    return out


def _adjust_scores(scores: np.ndarray, valid: np.ndarray, feats: dict[str, np.ndarray], strategy: str) -> tuple[np.ndarray, np.ndarray]:
    if strategy != "improved":
        return scores, valid
    ret20 = feats.get("ret_20d", 0.0)
    bias20 = feats.get("bias_20", 0.0)
    vol20 = feats.get("volatility_20d", 0.0)
    flow = feats.get("main_force_amount_ratio_5d", 0.0)
    adjusted = scores + 0.18 * ret20 + 0.12 * bias20 + 0.06 * flow - 0.10 * vol20
    trend_ok = (ret20 > -0.35) & (bias20 > -0.50) & (vol20 < 2.25)
    return adjusted, valid & trend_ok


@torch.no_grad()
def main() -> None:
    p = argparse.ArgumentParser(
        description=(
            "Equal-weight top-N backtest with sell-k/buy-k rebalancing. "
            "First day: buy top_n stocks equally. Later: sell the k lowest-score current holdings "
            "and buy the highest-score valid stocks not already held."
        )
    )
    p.add_argument("--panel", required=True, help="Path to panel .npz generated by load_data.py")
    p.add_argument("--checkpoint", required=True, help="Path to model checkpoint, e.g. best.pt")
    p.add_argument("--seq_len", type=int, default=30)
    p.add_argument("--start", type=str, default="2025-01-01", help="Backtest start decision date")
    p.add_argument("--end", type=str, default=None, help="Backtest end decision date")
    p.add_argument("--top_n", type=int, default=30, help="Target number of holdings")
    p.add_argument("--k", type=int, default=5, help="Number of stocks to sell and buy each rebalance day")
    p.add_argument("--fee", type=float, default=0.001, help="One-way turnover cost, e.g. 0.001 means 10 bps")
    p.add_argument("--strategy", type=str, default="baseline", choices=["baseline", "improved"])
    p.add_argument("--rebalance_interval", type=int, default=1, help="Score-based rebalance interval in trading days")
    p.add_argument("--stop_loss", type=float, default=-0.035, help="Sell a held stock after a realized one-day loss below this value")
    p.add_argument("--out", type=str, default="back_test_equal.csv", help="Daily backtest result CSV")
    p.add_argument("--holdings_out", type=str, default=None, help="Optional long-format daily holdings CSV")
    p.add_argument("--metrics_out", type=str, default=None, help="Optional JSON metrics output")
    p.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    args = p.parse_args()

    if args.top_n <= 0:
        raise ValueError("--top_n must be positive.")
    if args.k <= 0:
        raise ValueError("--k must be positive.")
    if args.k > args.top_n:
        raise ValueError("--k should not be larger than --top_n.")
    if args.rebalance_interval <= 0:
        raise ValueError("--rebalance_interval must be positive.")

    ds = StockPanelDataset(args.panel, seq_len=args.seq_len)
    sample_dates = ds.dates[ds.end_indices]
    start = pd.Timestamp(args.start)
    end = pd.Timestamp(args.end) if args.end else pd.Timestamp.max
    sample_indices = np.where((sample_dates >= start) & (sample_dates <= end))[0].tolist()
    if not sample_indices:
        raise ValueError("No backtest samples in requested date range.")

    ckpt = _safe_load_checkpoint(args.checkpoint, args.device)
    model = rebuild_model(ckpt, num_features=len(ds.feature_cols)).to(args.device)
    model.load_state_dict(ckpt["model_state"])
    model.eval()

    stocks = ds.stocks.astype(str)
    num_stocks = len(stocks)
    holdings: list[int] = []
    prev_w: np.ndarray | None = None
    nav = 1.0
    rows: list[dict] = []
    holdings_rows: list[dict] = []
    prev_stock_returns: np.ndarray | None = None

    for step, ds_idx in enumerate(sample_indices):
        x, y, m, date_str = ds[ds_idx]
        x = x.unsqueeze(0).to(args.device)  # (1, N, T, F)
        scores = model(x).squeeze(0).detach().cpu().numpy().astype(np.float64)
        returns = y.numpy().astype(np.float64)
        valid = (m.numpy() > 0) & np.isfinite(scores) & np.isfinite(returns)
        feats = _feature_values(x.squeeze(0).cpu(), ds.feature_cols, ["ret_20d", "bias_20", "volatility_20d", "main_force_amount_ratio_5d"])
        trade_scores, buy_valid = _adjust_scores(scores, valid, feats, args.strategy)

        ranked_high = _rank_valid_indices(trade_scores, buy_valid, descending=True)
        if len(ranked_high) < min(args.top_n, int(valid.sum())):
            fallback = _rank_valid_indices(trade_scores, valid, descending=True)
            ranked_high = ranked_high + [i for i in fallback if i not in set(ranked_high)]
        if len(ranked_high) == 0:
            raise ValueError(f"No valid stocks on {date_str}; cannot continue backtest.")

        sold: list[int] = []
        bought: list[int] = []

        if step == 0:
            # First day: build an equal-weight portfolio using the highest-score valid stocks.
            holdings = ranked_high[: min(args.top_n, len(ranked_high))]
            bought = holdings.copy()
        else:
            holding_set = set(holdings)

            stop_held: list[int] = []
            if args.strategy == "improved" and prev_stock_returns is not None:
                stop_held = [i for i in holdings if np.isfinite(prev_stock_returns[i]) and prev_stock_returns[i] <= args.stop_loss]

            invalid_held = [i for i in holdings if not valid[i]]
            forced = []
            for i in invalid_held + stop_held:
                if i not in forced:
                    forced.append(i)
            score_rebalance = step % args.rebalance_interval == 0
            sell_quota = max(args.k if score_rebalance else 0, len(forced))

            def sell_score(i: int) -> float:
                if i in forced:
                    return -np.inf
                return float(trade_scores[i]) if valid[i] and np.isfinite(trade_scores[i]) else -np.inf

            sell_candidates = sorted(holdings, key=sell_score)
            sold = sell_candidates[: min(sell_quota, len(sell_candidates))]
            holding_set.difference_update(sold)

            target_count = min(args.top_n, len(ranked_high))
            for candidate in ranked_high:
                if len(holding_set) >= target_count:
                    break
                if candidate in holding_set:
                    continue
                holding_set.add(candidate)
                bought.append(candidate)

            # Keep holdings ordered by current score from high to low for readable output.
            holdings = [i for i in ranked_high if i in holding_set]

        w = _make_equal_weight_vector(num_stocks, holdings)
        gross_ret = float(np.nansum(w * returns))
        turnover = 1.0 if prev_w is None else float(np.abs(w - prev_w).sum())
        net_ret = gross_ret - args.fee * turnover
        nav *= 1.0 + net_ret

        rows.append(
            {
                "date": date_str,
                "gross_ret": gross_ret,
                "turnover": turnover,
                "cost": args.fee * turnover,
                "net_ret": net_ret,
                "nav": nav,
                "holding_count": len(holdings),
                "sold_count": len(sold),
                "bought_count": len(bought),
                "strategy": args.strategy,
                "rebalance": bool(step == 0 or step % args.rebalance_interval == 0),
                "sold": _format_codes(sold, stocks),
                "bought": _format_codes(bought, stocks),
                "holdings": _format_codes(holdings, stocks),
            }
        )

        for rank, stock_idx in enumerate(holdings, start=1):
            holdings_rows.append(
                {
                    "date": date_str,
                    "rank_in_portfolio": rank,
                    "ts_code": stocks[stock_idx],
                    "score": scores[stock_idx],
                    "trade_score": trade_scores[stock_idx],
                    "weight": w[stock_idx],
                    "target_return": returns[stock_idx],
                }
            )

        prev_w = w
        prev_stock_returns = returns

    res = pd.DataFrame(rows)
    daily = res["net_ret"].to_numpy(dtype=float)
    ann_ret = float(nav ** (252 / max(len(res), 1)) - 1.0)
    sharpe = float(daily.mean() / (daily.std() + 1e-12) * np.sqrt(252))
    max_dd = _calc_max_drawdown(res["nav"])
    win_rate = float((daily > 0).mean()) if len(daily) else float("nan")
    ann_vol = float(daily.std() * np.sqrt(252))
    final_return = float(nav - 1.0)

    out_path = Path(args.out)
    res.to_csv(out_path, index=False, encoding="utf-8-sig")

    holdings_out = Path(args.holdings_out) if args.holdings_out else out_path.with_name(out_path.stem + "_holdings.csv")
    pd.DataFrame(holdings_rows).to_csv(holdings_out, index=False, encoding="utf-8-sig")
    metrics = {
        "days": len(res),
        "top_n": args.top_n,
        "k": args.k,
        "fee": args.fee,
        "strategy": args.strategy,
        "rebalance_interval": args.rebalance_interval,
        "ann_ret": ann_ret,
        "ann_vol": ann_vol,
        "sharpe": sharpe,
        "max_drawdown": max_dd,
        "win_rate": win_rate,
        "final_nav": float(nav),
        "final_return": final_return,
        "avg_turnover": float(res["turnover"].mean()),
    }
    metrics_out = Path(args.metrics_out) if args.metrics_out else out_path.with_name(out_path.stem + "_metrics.json")
    metrics_out.write_text(json.dumps(metrics, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"Saved daily backtest to {out_path}")
    print(f"Saved daily holdings to {holdings_out}")
    print(f"Saved metrics to {metrics_out}")
    print(metrics)


if __name__ == "__main__":
    main()
