import os

import torch
from torchvision import datasets
from torchvision.transforms import v2
from torch.utils.data import DataLoader, Dataset

# Helper functions for the CIFAKE dataset
# Those functions are generated by GPT-5.4 mini

def download_cifake_dataset(output_dir: str = "./data/CIFAKE"):
    import kagglehub
    kagglehub.dataset_download(
        "birdy654/cifake-real-and-ai-generated-synthetic-images",
        output_dir=output_dir,
        )
    
def get_image_list(data_dir: str = "./data/CIFAKE", partition: str = "train"):
    import os
    image_dir = os.path.join(data_dir, partition)
    image_list_real = []
    image_list_fake = []
    for filename in os.listdir(image_dir):
        if filename.endswith(".jpg"):
            if "real" in filename:
                image_list_real.append(os.path.join(image_dir, filename))
            elif "fake" in filename:
                image_list_fake.append(os.path.join(image_dir, filename))
    return image_list_real, image_list_fake


def _build_imagefolder(data_dir: str, partition: str):
    transform = v2.Compose([
        v2.ToImage(),
        v2.ToDtype(torch.float32, scale=True),
    ])
    return datasets.ImageFolder(os.path.join(data_dir, partition), transform=transform)


def _balanced_class_pools(dataset, per_class: int, seed: int):
    targets = torch.as_tensor(dataset.targets)
    generator = torch.Generator().manual_seed(seed)
    class_pools = {}

    for label in sorted(targets.unique().tolist()):
        class_indices = torch.nonzero(targets == label, as_tuple=True)[0]
        shuffled = class_indices[torch.randperm(len(class_indices), generator=generator)]
        class_pools[int(label)] = shuffled[:per_class]

    return class_pools


def _shuffle_indices(indices: torch.Tensor, seed: int):
    generator = torch.Generator().manual_seed(seed)
    permutation = torch.randperm(len(indices), generator=generator)
    return indices[permutation]


def _materialize_tensor_split(dataset, indices, with_labels: bool):
    images = []
    labels = []

    for index in indices:
        image, label = dataset[int(index)]
        images.append(image)
        if with_labels:
            labels.append(label)

    image_tensor = torch.stack(images)
    if with_labels:
        label_tensor = torch.tensor(labels, dtype=torch.long)
        return image_tensor, label_tensor
    return image_tensor

def get_dataset_tensor():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(base_dir, "data", "CIFAKE")
    output_dir = os.path.join(base_dir, "data")

    train_dataset = _build_imagefolder(data_dir, "train")
    test_dataset = _build_imagefolder(data_dir, "test")

    # Keep a balanced 50k train subset and a balanced 10k test subset.
    train_pools = _balanced_class_pools(train_dataset, per_class=25000, seed=42)
    test_pools = _balanced_class_pools(test_dataset, per_class=5000, seed=43)
    class_labels = sorted(train_pools.keys())

    test_indices = torch.cat([test_pools[label] for label in class_labels])
    test_indices = _shuffle_indices(test_indices, seed=44)
    test_images, test_labels = _materialize_tensor_split(test_dataset, test_indices, with_labels=True)

    ratio_configs = {
        "r1": 250,
        "r10": 2500,
    }

    results = {}
    for ratio_name, labelled_per_class in ratio_configs.items():
        ratio_dir = os.path.join(output_dir, ratio_name)
        os.makedirs(ratio_dir, exist_ok=True)

        pretrain_path = os.path.join(ratio_dir, "pretrain.pth")
        finetune_path = os.path.join(ratio_dir, "finetune.pth")
        test_path = os.path.join(ratio_dir, "test.pth")

        labelled_indices = torch.cat([
            train_pools[label][:labelled_per_class] for label in class_labels
        ])
        labelled_indices = _shuffle_indices(labelled_indices, seed=100 + labelled_per_class)

        pretrain_indices = torch.cat([
            train_pools[label][labelled_per_class:] for label in class_labels
        ])
        pretrain_indices = _shuffle_indices(pretrain_indices, seed=200 + labelled_per_class)

        if not os.path.exists(pretrain_path):
            pretrain_images = _materialize_tensor_split(train_dataset, pretrain_indices, with_labels=False)
            torch.save(pretrain_images, pretrain_path)

        if not os.path.exists(finetune_path):
            finetune_images, finetune_labels = _materialize_tensor_split(train_dataset, labelled_indices, with_labels=True)
            torch.save((finetune_images, finetune_labels), finetune_path)

        if not os.path.exists(test_path):
            torch.save((test_images, test_labels), test_path)

        results[ratio_name] = {
            "pretrain": pretrain_path,
            "finetune": finetune_path,
            "test": test_path,
        }

        print(
            f"{ratio_name}: "
            f"pretrain={tuple(torch.load(pretrain_path).shape)}, "
            f"finetune={tuple(torch.load(finetune_path)[0].shape)}, "
            f"test={tuple(torch.load(test_path)[0].shape)}"
        )

    return results

# Dataloader part

CIFAR10_MEAN = (0.4914, 0.4822, 0.4465)
CIFAR10_STD = (0.2470, 0.2435, 0.2616)

class TwoCropsTransform:
    # x -> (t1(x), t2(x))
    
    def __init__(self, base_transform):
        self.base_transform = base_transform
        
    def __call__(self, x):
        view_1 = self.base_transform(x)
        view_2 = self.base_transform(x)
        return view_1, view_2


class SimCLRPretrainDataset(Dataset):
    def __init__(self, images: torch.Tensor, transform):
        self.images = images
        self.transform = transform

    def __len__(self):
        return len(self.images)

    def __getitem__(self, index):
        return self.transform(self.images[index])


class ClassificationTensorDataset(Dataset):
    def __init__(self, images: torch.Tensor, labels: torch.Tensor, transform):
        self.images = images
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.images)

    def __getitem__(self, index):
        return self.transform(self.images[index]), self.labels[index]
    
def get_simclr_cifar10_transform(
    image_size: int = 32,
    color_jitter_strength: float = 0.5,
    use_blur: bool = False,
):
    color_jitter = v2.ColorJitter(
        brightness=0.8 * color_jitter_strength,
        contrast=0.8 * color_jitter_strength,
        saturation=0.8 * color_jitter_strength,
        hue=0.2 * color_jitter_strength,
    )
    
    transform_list = [
        v2.ToPILImage(),
        v2.RandomResizedCrop(
            size = image_size,
            scale = (0.08, 1.0), # NOTE: 0.08 is quite agressive for 32x32 images
            ratio = (3.0 / 4.0, 4.0 / 3.0),
        ),
        v2.RandomHorizontalFlip(p=0.5),
        v2.RandomApply([color_jitter], p=0.8),
        v2.RandomGrayscale(p=0.2),
    ]

    if use_blur:
        kernel_size = 5

        transform_list.append(
            v2.RandomApply(
                [v2.GaussianBlur(kernel_size=kernel_size, sigma=(0.1, 2.0))],
                p=0.5,
            )
        )
        
    transform_list.extend(
        [
            v2.ToImage(),
            v2.ToDtype(torch.float32, scale=True),
            v2.Normalize(CIFAR10_MEAN, CIFAR10_STD),
        ]
    )
    
    return v2.Compose(transform_list)


def get_cifar10_classification_transform(train: bool = False):
    transform_list = [v2.ToPILImage()]
    if train:
        transform_list.extend([
            v2.RandomCrop(32, padding=4),
            v2.RandomHorizontalFlip(p=0.5),
        ])
    transform_list.extend([
        v2.ToImage(),
        v2.ToDtype(torch.float32, scale=True),
        v2.Normalize(CIFAR10_MEAN, CIFAR10_STD),
    ])
    return v2.Compose(transform_list)

def get_cifar10_simclr_dataloader(
    data_dir: str = "./data/r10/pretrain.pth",
    batch_size: int = 8192,
    use_blur: bool = False,
) -> DataLoader:
    
    base_transform = get_simclr_cifar10_transform(use_blur=use_blur)
    simclr_transform = TwoCropsTransform(base_transform)
    
    images = torch.load(data_dir)
    train_dataset = SimCLRPretrainDataset(images, simclr_transform)
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        num_workers=8,
        pin_memory=True,
        persistent_workers=True,
        multiprocessing_context="spawn",
        drop_last=True
    )
    
    return train_loader


def get_cifar10_classification_dataloader(
    data_dir: str = "./data/r10/finetune.pth",
    batch_size: int = 256,
    train: bool = True,
) -> DataLoader:
    images, labels = torch.load(data_dir)
    dataset = ClassificationTensorDataset(
        images,
        labels,
        get_cifar10_classification_transform(train=train),
    )
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=train,
        num_workers=8,
        pin_memory=True,
        persistent_workers=True,
        multiprocessing_context="spawn",
    )
